In [1]:
import pandas

In [2]:
dataset = pandas.read_csv('50_Startups.csv')

In [3]:
# Here y = Profit

dataset

    R&D Spend  Administration  Marketing Spend       State     Profit
0   165349.20       136897.80        471784.10    New York  192261.83
1   162597.70       151377.59        443898.53  California  191792.06
2   153441.51       101145.55        407934.54     Florida  191050.39
3   144372.41       118671.85        383199.62    New York  182901.99
4   142107.34        91391.77        366168.42     Florida  166187.94
5   131876.90        99814.71        362861.36    New York  156991.12
6   134615.46       147198.87        127716.82  California  156122.51
7   130298.13       145530.06        323876.68     Florida  155752.60
8   120542.52       148718.95        311613.29    New York  152211.77
9   123334.88       108679.17        304981.62  California  149759.96
10  101913.08       110594.11        229160.95     Florida  146121.95
11  100671.96        91790.61        249744.55  California  144259.40
12   93863.75       127320.38        249839.44     Florida  141585.52
13   91992.39       135495.07        252664.93  California  134307.35
14  119943.24       156547.42        256512.92     Florida  132602.65
15  114523.61       122616.84        261776.23    New York  129917.04
16   78013.11       121597.55        264346.06  California  126992.93
17   94657.16       145077.58        282574.31    New York  125370.37
18   91749.16       114175.79        294919.57     Florida  124266.90
19   86419.70       153514.11             0.00    New York  122776.86
20   76253.86       113867.30        298664.47  California  118474.03
21   78389.47       153773.43        299737.29    New York  111313.02
22   73994.56       122782.75        303319.26     Florida  110352.25
23   67532.53       105751.03        304768.73     Florida  108733.99
24   77044.01        99281.34        140574.81    New York  108552.04
25   64664.71       139553.16        137962.62  California  107404.34
26   75328.87       144135.98        134050.07     Florida  105733.54
27   72107.60       127864.55        353183.81    New York  105008.31
28   66051.52       182645.56        118148.20     Florida  103282.38
29   65605.48       153032.06        107138.38    New York  101004.64
30   61994.48       115641.28         91131.24     Florida   99937.59
31   61136.38       152701.92         88218.23    New York   97483.56
32   63408.86       129219.61         46085.25  California   97427.84
33   55493.95       103057.49        214634.81     Florida   96778.92
34   46426.07       157693.92        210797.67  California   96712.80
35   46014.02        85047.44        205517.64    New York   96479.51
36   28663.76       127056.21        201126.82     Florida   90708.19
37   44069.95        51283.14        197029.42  California   89949.14
38   20229.59        65947.93        185265.10    New York   81229.06
39   38558.51        82982.09        174999.30  California   81005.76
40   28754.33       118546.05        172795.67  California   78239.91
41   27892.92        84710.77        164470.71     Florida   77798.83
42   23640.93        96189.63        148001.11  California   71498.49
43   15505.73       127382.30         35534.17    New York   69758.98
44   22177.74       154806.14         28334.72  California   65200.33
45    1000.23       124153.04          1903.93    New York   64926.08
46    1315.46       115816.21        297114.46     Florida   49490.75
47       0.00       135426.92             0.00  California   42559.73
48     542.05        51743.15             0.00    New York   35673.41
49       0.00       116983.80         45173.06  California   14681.40

In [4]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   R&D Spend        50 non-null     float64
 1   Administration   50 non-null     float64
 2   Marketing Spend  50 non-null     float64
 3   State            50 non-null     object
 4   Profit           50 non-null     float64
dtypes: float64(4), object(1)
memory usage: 2.1+ KB

In [5]:
dataset.describe()

           R&D Spend  Administration  Marketing Spend         Profit
count      50.000000       50.000000        50.000000      50.000000
mean    73721.615600   121344.639600    211025.097800  112012.639200
std     45902.256482    28017.802755    122290.310726   40306.180338
min         0.000000    51283.140000         0.000000   14681.400000
25%     39936.370000   103730.875000    129300.132500   90138.902500
50%     73051.080000   122699.795000    212716.240000  107978.190000
75%    101602.800000   144842.180000    299469.085000  139765.977500
max    165349.200000   182645.560000    471784.100000  192261.830000

In [6]:
y = dataset['Profit']

In [7]:
dataset.columns

Index(['R&D Spend', 'Administration', 'Marketing Spend', 'State', 'Profit'], dtype='object')

In [8]:
x = dataset[ ['R&D Spend', 'Administration', 'Marketing Spend'] ]

In [9]:
state = dataset['State']

In [10]:
# In Dummy variables, we always remove a feature(column) dependent on another column. Categorical variable. 
# We need to add "drop_first=True" for the dependent Feature Elimination.

dummy_state = pandas.get_dummies(state, drop_first=True)

In [11]:
# This is a Dummy Variable & This type is Boolean. True = 1  & False = 0
# dummy_state is also a part of x

dummy_state

    Florida  New York
0     False      True
1     False     False
2      True     False
3     False      True
4      True     False
5     False      True
6     False     False
7      True     False
8     False      True
9     False     False
10     True     False
11    False     False
12     True     False
13    False     False
14     True     False
15    False      True
16    False     False
17    False      True
18     True     False
19    False      True
20    False     False
21    False      True
22     True     False
23     True     False
24    False      True
25    False     False
26     True     False
27    False      True
28     True     False
29    False      True
30     True     False
31    False      True
32    False     False
33     True     False
34    False     False
35    False      True
36     True     False
37    False     False
38    False      True
39    False     False
40    False     False
41     True     False
42    False     False
43    False      True
44    False     False
45    False      True
46     True     False
47    False     False
48    False      True
49    False     False

In [12]:
# We already have value for "x". And we added Florida & New York inside x. Means, take dataset from "dummy_state"


x[ ["Florida", "New York"]  ] = dummy_state

C:\Users\rahul\AppData\Local\Temp\ipykernel_13992\1566879874.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x[ ["Florida", "New York"]  ] = dummy_state

In [13]:
x

    R&D Spend  Administration  Marketing Spend  Florida  New York
0   165349.20       136897.80        471784.10    False      True
1   162597.70       151377.59        443898.53    False     False
2   153441.51       101145.55        407934.54     True     False
3   144372.41       118671.85        383199.62    False      True
4   142107.34        91391.77        366168.42     True     False
5   131876.90        99814.71        362861.36    False      True
6   134615.46       147198.87        127716.82    False     False
7   130298.13       145530.06        323876.68     True     False
8   120542.52       148718.95        311613.29    False      True
9   123334.88       108679.17        304981.62    False     False
10  101913.08       110594.11        229160.95     True     False
11  100671.96        91790.61        249744.55    False     False
12   93863.75       127320.38        249839.44     True     False
13   91992.39       135495.07        252664.93    False     False
14  119943.24       156547.42        256512.92     True     False
15  114523.61       122616.84        261776.23    False      True
16   78013.11       121597.55        264346.06    False     False
17   94657.16       145077.58        282574.31    False      True
18   91749.16       114175.79        294919.57     True     False
19   86419.70       153514.11             0.00    False      True
20   76253.86       113867.30        298664.47    False     False
21   78389.47       153773.43        299737.29    False      True
22   73994.56       122782.75        303319.26     True     False
23   67532.53       105751.03        304768.73     True     False
24   77044.01        99281.34        140574.81    False      True
25   64664.71       139553.16        137962.62    False     False
26   75328.87       144135.98        134050.07     True     False
27   72107.60       127864.55        353183.81    False      True
28   66051.52       182645.56        118148.20     True     False
29   65605.48       153032.06        107138.38    False      True
30   61994.48       115641.28         91131.24     True     False
31   61136.38       152701.92         88218.23    False      True
32   63408.86       129219.61         46085.25    False     False
33   55493.95       103057.49        214634.81     True     False
34   46426.07       157693.92        210797.67    False     False
35   46014.02        85047.44        205517.64    False      True
36   28663.76       127056.21        201126.82     True     False
37   44069.95        51283.14        197029.42    False     False
38   20229.59        65947.93        185265.10    False      True
39   38558.51        82982.09        174999.30    False     False
40   28754.33       118546.05        172795.67    False     False
41   27892.92        84710.77        164470.71     True     False
42   23640.93        96189.63        148001.11    False     False
43   15505.73       127382.30         35534.17    False      True
44   22177.74       154806.14         28334.72    False     False
45    1000.23       124153.04          1903.93    False      True
46    1315.46       115816.21        297114.46     True     False
47       0.00       135426.92             0.00    False     False
48     542.05        51743.15             0.00    False      True
49       0.00       116983.80         45173.06    False     False

In [14]:
from sklearn.linear_model import LinearRegression

In [15]:
model = LinearRegression()

In [16]:
model.fit(x, y)

LinearRegression()

In [17]:
model.coef_

array([ 8.06023114e-01, -2.70043196e-02,  2.69798610e-02,  1.98788793e+02,
       -4.18870191e+01])

In [18]:
x

    R&D Spend  Administration  Marketing Spend  Florida  New York
0   165349.20       136897.80        471784.10    False      True
1   162597.70       151377.59        443898.53    False     False
2   153441.51       101145.55        407934.54     True     False
3   144372.41       118671.85        383199.62    False      True
4   142107.34        91391.77        366168.42     True     False
5   131876.90        99814.71        362861.36    False      True
6   134615.46       147198.87        127716.82    False     False
7   130298.13       145530.06        323876.68     True     False
8   120542.52       148718.95        311613.29    False      True
9   123334.88       108679.17        304981.62    False     False
10  101913.08       110594.11        229160.95     True     False
11  100671.96        91790.61        249744.55    False     False
12   93863.75       127320.38        249839.44     True     False
13   91992.39       135495.07        252664.93    False     False
14  119943.24       156547.42        256512.92     True     False
15  114523.61       122616.84        261776.23    False      True
16   78013.11       121597.55        264346.06    False     False
17   94657.16       145077.58        282574.31    False      True
18   91749.16       114175.79        294919.57     True     False
19   86419.70       153514.11             0.00    False      True
20   76253.86       113867.30        298664.47    False     False
21   78389.47       153773.43        299737.29    False      True
22   73994.56       122782.75        303319.26     True     False
23   67532.53       105751.03        304768.73     True     False
24   77044.01        99281.34        140574.81    False      True
25   64664.71       139553.16        137962.62    False     False
26   75328.87       144135.98        134050.07     True     False
27   72107.60       127864.55        353183.81    False      True
28   66051.52       182645.56        118148.20     True     False
29   65605.48       153032.06        107138.38    False      True
30   61994.48       115641.28         91131.24     True     False
31   61136.38       152701.92         88218.23    False      True
32   63408.86       129219.61         46085.25    False     False
33   55493.95       103057.49        214634.81     True     False
34   46426.07       157693.92        210797.67    False     False
35   46014.02        85047.44        205517.64    False      True
36   28663.76       127056.21        201126.82     True     False
37   44069.95        51283.14        197029.42    False     False
38   20229.59        65947.93        185265.10    False      True
39   38558.51        82982.09        174999.30    False     False
40   28754.33       118546.05        172795.67    False     False
41   27892.92        84710.77        164470.71     True     False
42   23640.93        96189.63        148001.11    False     False
43   15505.73       127382.30         35534.17    False      True
44   22177.74       154806.14         28334.72    False     False
45    1000.23       124153.04          1903.93    False      True
46    1315.46       115816.21        297114.46     True     False
47       0.00       135426.92             0.00    False     False
48     542.05        51743.15             0.00    False      True
49       0.00       116983.80         45173.06    False     False

In [19]:
model.predict(x)

array([192390.57136321, 189071.32010494, 182276.18673283, 173584.97618975,
       172277.13381666, 163473.8071184 , 158099.29278417, 160155.64464939,
       151634.74332631, 154829.66252708, 135664.64259063, 135528.60078159,
       129282.91780691, 127431.24898633, 149694.3827755 , 146143.63551378,
       116854.0745287 , 130085.40993359, 129149.72574273, 115594.18840731,
       116570.73444001, 117201.50508976, 114833.30513844, 110123.79610587,
       113294.37345153, 102200.26891867, 110765.3011688 , 114279.80403012,
       101818.58738693, 101721.04202942,  99629.0105373 ,  97617.29632021,
        98988.23660304,  98061.35894838,  88974.70416296,  90420.00960609,
        75423.09286561,  89577.70222194,  69606.52160902,  83684.9760399 ,
        74762.74617648,  74956.31104907,  70575.99371382,  60100.2682187 ,
        64585.14721293,  47588.36470994,  56272.99268497,  46468.23200485,
        49123.07308284,  48185.0387926 ])

In [20]:


from sklearn.model_selection import train_test_split

In [21]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.20, random_state=42)

In [22]:
x_train

    R&D Spend  Administration  Marketing Spend  Florida  New York
12   93863.75       127320.38        249839.44     True     False
4   142107.34        91391.77        366168.42     True     False
37   44069.95        51283.14        197029.42    False     False
8   120542.52       148718.95        311613.29    False      True
3   144372.41       118671.85        383199.62    False      True
6   134615.46       147198.87        127716.82    False     False
41   27892.92        84710.77        164470.71     True     False
46    1315.46       115816.21        297114.46     True     False
47       0.00       135426.92             0.00    False     False
15  114523.61       122616.84        261776.23    False      True
9   123334.88       108679.17        304981.62    False     False
16   78013.11       121597.55        264346.06    False     False
24   77044.01        99281.34        140574.81    False      True
34   46426.07       157693.92        210797.67    False     False
31   61136.38       152701.92         88218.23    False      True
0   165349.20       136897.80        471784.10    False      True
44   22177.74       154806.14         28334.72    False     False
27   72107.60       127864.55        353183.81    False      True
33   55493.95       103057.49        214634.81     True     False
5   131876.90        99814.71        362861.36    False      True
29   65605.48       153032.06        107138.38    False      True
11  100671.96        91790.61        249744.55    False     False
36   28663.76       127056.21        201126.82     True     False
1   162597.70       151377.59        443898.53    False     False
21   78389.47       153773.43        299737.29    False      True
2   153441.51       101145.55        407934.54     True     False
43   15505.73       127382.30         35534.17    False      True
35   46014.02        85047.44        205517.64    False      True
23   67532.53       105751.03        304768.73     True     False
40   28754.33       118546.05        172795.67    False     False
10  101913.08       110594.11        229160.95     True     False
22   73994.56       122782.75        303319.26     True     False
18   91749.16       114175.79        294919.57     True     False
49       0.00       116983.80         45173.06    False     False
20   76253.86       113867.30        298664.47    False     False
7   130298.13       145530.06        323876.68     True     False
42   23640.93        96189.63        148001.11    False     False
14  119943.24       156547.42        256512.92     True     False
28   66051.52       182645.56        118148.20     True     False
38   20229.59        65947.93        185265.10    False      True

In [23]:
x_test

    R&D Spend  Administration  Marketing Spend  Florida  New York
13   91992.39       135495.07        252664.93    False     False
39   38558.51        82982.09        174999.30    False     False
30   61994.48       115641.28         91131.24     True     False
45    1000.23       124153.04          1903.93    False      True
17   94657.16       145077.58        282574.31    False      True
48     542.05        51743.15             0.00    False      True
26   75328.87       144135.98        134050.07     True     False
25   64664.71       139553.16        137962.62    False     False
32   63408.86       129219.61         46085.25    False     False
19   86419.70       153514.11             0.00    False      True