In [1]:
import pandas

In [2]:
dataset = pandas.read_csv('wine.csv')

In [3]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Wine                  178 non-null    int64
 1   Alcohol               178 non-null    float64
 2   Malic.acid            178 non-null    float64
 3   Ash                   178 non-null    float64
 4   Acl                   178 non-null    float64
 5   Mg                    178 non-null    int64
 6   Phenols               178 non-null    float64
 7   Flavanoids            178 non-null    float64
 8   Nonflavanoid.phenols  178 non-null    float64
 9   Proanth               178 non-null    float64
 10  Color.int             178 non-null    float64
 11  Hue                   178 non-null    float64
 12  OD                    178 non-null    float64
 13  Proline               178 non-null    int64
dtypes: float64(11), int64(3)
memory usage: 19.6 KB

In [4]:
dataset

,Wine,Alcohol,Malic.acid,Ash,Acl,Mg,Phenols,Flavanoids,Nonflavanoid.phenols,Proanth,Color.int,Hue,OD,Proline
0,1,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,1,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,3,13.71,5.65,2.45,20.5,95,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740
174,3,13.40,3.91,2.48,23.0,102,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750
175,3,13.27,4.28,2.26,20.0,120,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835
176,3,13.17,2.59,2.37,20.0,120,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840
177,3,14.13,4.10,2.74,24.5,96,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560

In [5]:
y = dataset['Wine']

In [6]:
y

0      1
1      1
2      1
3      1
4      1
      ..
173    3
174    3
175    3
176    3
177    3
Name: Wine, Length: 178, dtype: int64

In [7]:
dataset.columns

Index(['Wine', 'Alcohol', 'Malic.acid', 'Ash', 'Acl', 'Mg', 'Phenols',
       'Flavanoids', 'Nonflavanoid.phenols', 'Proanth', 'Color.int', 'Hue',
       'OD', 'Proline'],
      dtype='object')

In [8]:
y_cat = pandas.get_dummies(y)

In [9]:
# Neural network selects the feature from X automatically. No need to do feature elemination manually.

In [10]:
X = dataset[  ['Alcohol', 'Malic.acid', 'Ash', 'Acl', 'Mg', 'Phenols',
       'Flavanoids', 'Nonflavanoid.phenols', 'Proanth', 'Color.int', 'Hue',
       'OD', 'Proline']  ]

In [11]:
y_cat

         1      2      3
0     True  False  False
1     True  False  False
2     True  False  False
3     True  False  False
4     True  False  False
..     ...    ...    ...
173  False  False   True
174  False  False   True
175  False  False   True
176  False  False   True
177  False  False   True

[178 rows x 3 columns]

In [12]:
X

,Alcohol,Malic.acid,Ash,Acl,Mg,Phenols,Flavanoids,Nonflavanoid.phenols,Proanth,Color.int,Hue,OD,Proline
0,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735
...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,13.71,5.65,2.45,20.5,95,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740
174,13.40,3.91,2.48,23.0,102,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750
175,13.27,4.28,2.26,20.0,120,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835
176,13.17,2.59,2.37,20.0,120,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840
177,14.13,4.10,2.74,24.5,96,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560

In [13]:
from keras.models import Sequential

In [14]:
from keras.layers import Dense

In [15]:
model = Sequential()

In [16]:
model.add(   
        Dense(
                units=10, 
                input_dim=13,
                activation="relu",
                bias_initializer="zeros",
                kernel_initializer="zeros"
        
                )
        )

C:\Python312\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [17]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 10)                  │             140 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 140 (560.00 B)

 Trainable params: 140 (560.00 B)

 Non-trainable params: 0 (0.00 B)

In [18]:
model.add(   
        Dense(
                units=8, 
                activation="relu",
                bias_initializer="zeros",
                kernel_initializer="zeros"
        
                )
        )

In [19]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 10)                  │             140 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 8)                   │              88 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 228 (912.00 B)

 Trainable params: 228 (912.00 B)

 Non-trainable params: 0 (0.00 B)

In [20]:
model.layers[1]

In [21]:
model.layers[1].get_weights()

[array([[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32),
 array([0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)]

In [22]:
model.layers[0].output

In [23]:
model.layers[0].input

In [24]:
model.add(   
        Dense(
                units=8, 
                activation="relu",
                bias_initializer="zeros",
                kernel_initializer="zeros"
        
                )
        )

In [25]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 10)                  │             140 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 8)                   │              88 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 8)                   │              72 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 300 (1.17 KB)

 Trainable params: 300 (1.17 KB)

 Non-trainable params: 0 (0.00 B)

In [26]:
model.add(   
        Dense(
                units=3, 
                activation="softmax",
                bias_initializer="zeros",
                kernel_initializer="zeros"
        
                )
        )

In [27]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 10)                  │             140 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 8)                   │              88 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 8)                   │              72 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_3 (Dense)                      │ (None, 3)                   │              27 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 327 (1.28 KB)

 Trainable params: 327 (1.28 KB)

 Non-trainable params: 0 (0.00 B)

In [28]:
model.compile(loss="categorical_crossentropy")

In [29]:
model.fit(X, y_cat)

6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 1.0983

In [30]:
model.get_weights()

[array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32),
 array([[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32),
 array([0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32),
 array([[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32),
 array([0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32),
 array([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=float32),
 array([-0.00135562,  0.00475637, -0.01112842], dtype=float32)]

In [31]:
model.predict(X)

6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step

array([[0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755],
       [0.33373317, 0.3357792 , 0.33048755]], dtype=float32)